# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{topsy}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wynn Netherland", "Ernesto Tagwerker"]
  s.date = %q{2010-02-14}
  s.description = %q{Ruby wrapper for the Topsy otterapi}
  s.email = %q{wynn.netherland@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "TODO",
     "VERSION",
     "changelog.markdown",
     "lib/topsy.rb",
     "lib/topsy/author.rb",
     "lib/topsy/client.rb",
     "lib/topsy/link_search_result.rb",
     "lib/topsy/linkpost.rb",
     "lib/topsy/linkpost_count.rb",
     "lib/topsy/page.rb",
     "lib/topsy/rate_limit_info.rb",
     "lib/topsy/search_counts.rb",
     "lib/topsy/stats.rb",
     "lib/topsy/tag.rb",
     "lib/topsy/target.rb",
     "lib/topsy/trend.rb",
     "lib/topsy/tweet.rb",
     "lib/topsy/url_info.rb",
     "script/console",
     "script/destroy",
     "script/generate",
     "test/fixtures/authorinfo.json",
     "test/fixtures/authorsearch-page2.json",
     "test/fixtures/authorsearch.json",
     "test/fixtures/credit.json",
     "test/fixtures/linkpostcount.json",
     "test/fixtures/linkposts-page2.json",
     "test/fixtures/linkposts.json",
     "test/fixtures/profilesearch.json",
     "test/fixtures/related.json",
     "test/fixtures/search.json",
     "test/fixtures/searchcount.json",
     "test/fixtures/stats.json",
     "test/fixtures/tags.json",
     "test/fixtures/trackbacks.json",
     "test/fixtures/trending.json",
     "test/fixtures/urlinfo.json",
     "test/helper.rb",
     "test/test_topsy.rb",
     "topsy.gemspec"
  ]
  s.homepage = %q{http://github.com/pengwynn/topsy}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby wrapper for the Topsy otterapi}
  s.test_files = [
    "test/helper.rb",
     "test/test_topsy.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hashie>, ["~> 0.1.3"])
      s.add_runtime_dependency(%q<httparty>, ["~> 0.4.5"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 2.10.1"])
      s.add_development_dependency(%q<jnunemaker-matchy>, ["= 0.4.0"])
      s.add_development_dependency(%q<mocha>, ["= 0.9.4"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2.5"])
    else
      s.add_dependency(%q<hashie>, ["~> 0.1.3"])
      s.add_dependency(%q<httparty>, ["~> 0.4.5"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 2.10.1"])
      s.add_dependency(%q<jnunemaker-matchy>, ["= 0.4.0"])
      s.add_dependency(%q<mocha>, ["= 0.9.4"])
      s.add_dependency(%q<fakeweb>, [">= 1.2.5"])
    end
  else
    s.add_dependency(%q<hashie>, ["~> 0.1.3"])
    s.add_dependency(%q<httparty>, ["~> 0.4.5"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 2.10.1"])
    s.add_dependency(%q<jnunemaker-matchy>, ["= 0.4.0"])
    s.add_dependency(%q<mocha>, ["= 0.9.4"])
    s.add_dependency(%q<fakeweb>, [">= 1.2.5"])
  end
end

