# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{topsy}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wynn Netherland", "Ernesto Tagwerker"]
  s.date = %q{2010-01-06}
  s.description = %q{Ruby wrapper for the Topsy otterapi}
  s.email = %q{wynn.netherland@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown",
     "TODO"
  ]
  s.files = [
    ".gitignore",
     ".yardoc/checksums",
     ".yardoc/objects/Topsy.dat",
     ".yardoc/objects/Topsy/Author.dat",
     ".yardoc/objects/Topsy/Author/to_s_i.dat",
     ".yardoc/objects/Topsy/Author/type_i.dat",
     ".yardoc/objects/Topsy/Client.dat",
     ".yardoc/objects/Topsy/Client/author_info_i.dat",
     ".yardoc/objects/Topsy/Client/author_search_i.dat",
     ".yardoc/objects/Topsy/Client/credit_i.dat",
     ".yardoc/objects/Topsy/Client/get_rate_limit_status_i.dat",
     ".yardoc/objects/Topsy/Client/handle_response_i.dat",
     ".yardoc/objects/Topsy/Client/link_post_count_i.dat",
     ".yardoc/objects/Topsy/Client/link_posts_i.dat",
     ".yardoc/objects/Topsy/Client/mashup_i.dat",
     ".yardoc/objects/Topsy/Client/profile_search_i.dat",
     ".yardoc/objects/Topsy/Client/raise_errors_i.dat",
     ".yardoc/objects/Topsy/Client/related_i.dat",
     ".yardoc/objects/Topsy/Client/search_count_i.dat",
     ".yardoc/objects/Topsy/Client/search_i.dat",
     ".yardoc/objects/Topsy/Client/stats_i.dat",
     ".yardoc/objects/Topsy/Client/tags_i.dat",
     ".yardoc/objects/Topsy/Client/trackbacks_i.dat",
     ".yardoc/objects/Topsy/Client/trending_i.dat",
     ".yardoc/objects/Topsy/Client/url_info_i.dat",
     ".yardoc/objects/Topsy/LinkSearchResult.dat",
     ".yardoc/objects/Topsy/LinkSearchResult/to_s_i.dat",
     ".yardoc/objects/Topsy/Linkpost.dat",
     ".yardoc/objects/Topsy/Linkpost/target_3D_i.dat",
     ".yardoc/objects/Topsy/Linkpost/to_s_i.dat",
     ".yardoc/objects/Topsy/LinkpostCount.dat",
     ".yardoc/objects/Topsy/LinkpostCount/to_s_i.dat",
     ".yardoc/objects/Topsy/Page.dat",
     ".yardoc/objects/Topsy/Page/initialize_i.dat",
     ".yardoc/objects/Topsy/Page/list_3D_i.dat",
     ".yardoc/objects/Topsy/Page/to_s_i.dat",
     ".yardoc/objects/Topsy/RateLimitInfo.dat",
     ".yardoc/objects/Topsy/RateLimitInfo/refresh_in_seconds_i.dat",
     ".yardoc/objects/Topsy/RateLimitInfo/reset_i.dat",
     ".yardoc/objects/Topsy/SearchCounts.dat",
     ".yardoc/objects/Topsy/SearchCounts/all_time_i.dat",
     ".yardoc/objects/Topsy/SearchCounts/hour_i.dat",
     ".yardoc/objects/Topsy/SearchCounts/month_i.dat",
     ".yardoc/objects/Topsy/SearchCounts/overall_i.dat",
     ".yardoc/objects/Topsy/SearchCounts/this_hour_i.dat",
     ".yardoc/objects/Topsy/SearchCounts/this_month_i.dat",
     ".yardoc/objects/Topsy/SearchCounts/this_week_i.dat",
     ".yardoc/objects/Topsy/SearchCounts/today_i.dat",
     ".yardoc/objects/Topsy/SearchCounts/week_i.dat",
     ".yardoc/objects/Topsy/Stats.dat",
     ".yardoc/objects/Topsy/Stats/to_s_i.dat",
     ".yardoc/objects/Topsy/Tag.dat",
     ".yardoc/objects/Topsy/Tag/to_s_i.dat",
     ".yardoc/objects/Topsy/Target.dat",
     ".yardoc/objects/Topsy/Target/to_s_i.dat",
     ".yardoc/objects/Topsy/Trend.dat",
     ".yardoc/objects/Topsy/Trend/to_s_i.dat",
     ".yardoc/objects/Topsy/Tweet.dat",
     ".yardoc/objects/Topsy/Tweet/author_3D_i.dat",
     ".yardoc/objects/Topsy/Tweet/target_3D_i.dat",
     ".yardoc/objects/Topsy/Tweet/to_s_i.dat",
     ".yardoc/objects/Topsy/UrlInfo.dat",
     ".yardoc/objects/Topsy/UrlInfo/to_s_i.dat",
     ".yardoc/objects/root.dat",
     ".yardoc/proxy_types",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "TODO",
     "VERSION",
     "changelog.markdown",
     "doc/Topsy.html",
     "doc/Topsy/Author.html",
     "doc/Topsy/Client.html",
     "doc/Topsy/LinkSearchResult.html",
     "doc/Topsy/Linkpost.html",
     "doc/Topsy/LinkpostCount.html",
     "doc/Topsy/Page.html",
     "doc/Topsy/RateLimitInfo.html",
     "doc/Topsy/SearchCounts.html",
     "doc/Topsy/Stats.html",
     "doc/Topsy/Tag.html",
     "doc/Topsy/Target.html",
     "doc/Topsy/Trend.html",
     "doc/Topsy/Tweet.html",
     "doc/Topsy/UrlInfo.html",
     "doc/_index.html",
     "doc/class_list.html",
     "doc/css/common.css",
     "doc/css/full_list.css",
     "doc/css/style.css",
     "doc/file.README.html",
     "doc/file_list.html",
     "doc/index.html",
     "doc/js/app.js",
     "doc/js/full_list.js",
     "doc/js/jquery.js",
     "doc/method_list.html",
     "doc/top-level-namespace.html",
     "lib/topsy.rb",
     "lib/topsy/author.rb",
     "lib/topsy/client.rb",
     "lib/topsy/link_search_result.rb",
     "lib/topsy/linkpost.rb",
     "lib/topsy/linkpost_count.rb",
     "lib/topsy/page.rb",
     "lib/topsy/rate_limit_info.rb",
     "lib/topsy/search_counts.rb",
     "lib/topsy/stats.rb",
     "lib/topsy/tag.rb",
     "lib/topsy/target.rb",
     "lib/topsy/trend.rb",
     "lib/topsy/tweet.rb",
     "lib/topsy/url_info.rb",
     "script/console",
     "script/destroy",
     "script/generate",
     "test/fixtures/authorinfo.json",
     "test/fixtures/authorsearch.json",
     "test/fixtures/credit.json",
     "test/fixtures/linkpostcount.json",
     "test/fixtures/linkposts.json",
     "test/fixtures/profilesearch.json",
     "test/fixtures/related.json",
     "test/fixtures/search.json",
     "test/fixtures/searchcount.json",
     "test/fixtures/stats.json",
     "test/fixtures/tags.json",
     "test/fixtures/trackbacks.json",
     "test/fixtures/trending.json",
     "test/fixtures/urlinfo.json",
     "test/helper.rb",
     "test/test_topsy.rb",
     "topsy.gemspec"
  ]
  s.homepage = %q{http://github.com/pengwynn/topsy}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby wrapper for the Topsy otterapi}
  s.test_files = [
    "test/helper.rb",
     "test/test_topsy.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hashie>, ["~> 0.1.3"])
      s.add_runtime_dependency(%q<httparty>, ["~> 0.4.5"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 2.10.1"])
      s.add_development_dependency(%q<jnunemaker-matchy>, ["= 0.4.0"])
      s.add_development_dependency(%q<mocha>, ["= 0.9.4"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2.5"])
    else
      s.add_dependency(%q<hashie>, ["~> 0.1.3"])
      s.add_dependency(%q<httparty>, ["~> 0.4.5"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 2.10.1"])
      s.add_dependency(%q<jnunemaker-matchy>, ["= 0.4.0"])
      s.add_dependency(%q<mocha>, ["= 0.9.4"])
      s.add_dependency(%q<fakeweb>, [">= 1.2.5"])
    end
  else
    s.add_dependency(%q<hashie>, ["~> 0.1.3"])
    s.add_dependency(%q<httparty>, ["~> 0.4.5"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 2.10.1"])
    s.add_dependency(%q<jnunemaker-matchy>, ["= 0.4.0"])
    s.add_dependency(%q<mocha>, ["= 0.9.4"])
    s.add_dependency(%q<fakeweb>, [">= 1.2.5"])
  end
end

